In [1]:
import pandas as pd

In [2]:
emp = pd.read_excel('employee.xlsx')

In [3]:
emp

    Serial  Emp_ID Designation  Department   Age    Salary
0        1    1101     Manager    Accounts  50.0  200000.0
1        2    1107     Officer          IT  30.0   80000.0
2        3    1203     Officer          HR  28.0       NaN
3        4    1005     Manager          HR  45.0  120000.0
4        5    2123  Office Boy    Accounts  27.0   45000.0
5        6    2451  Accountant         NaN  34.0  100000.0
6        7    1111  Accountant    Accounts   NaN  110000.0
7        8    1001     Officer          IT  25.0   75000.0
8        9    1234     Manager          IT  23.0       NaN
9       10    2156    Engineer  Production  45.0   89000.0
10      11    6543     Officer  Production  29.0  100000.0
11      12    3214  Accountant     Account  49.0  123000.0
12      13    2156    Engineer  Production  45.0   89000.0
13      14    1098     Officer          IT  25.0  100000.0
14      15    2912     Officer          IT  31.0   90000.0
15      16    1222     Officer         NaN  25.0       NaN
16      17    2156    Engineer  Production  45.0   89000.0
17      18    2123  Office Boy    Accounts  27.0   45000.0

In [ ]:
def bonus(sal):
    if sal >= 200000:
        return sal * 0.5
    elif sal >= 150000:
        return sal * 0.3
    elif sal >= 100000:
        return sal * 0.25
    
    else:
        return sal * 0.1

In [ ]:
emp['Bonus']  = emp.Salary.apply(bonus)
emp

    Serial  Emp_ID Designation  Department   Age    Salary     Bonus
0        1    1101     Manager    Accounts  50.0  200000.0  100000.0
1        2    1107     Officer          IT  30.0   80000.0    8000.0
2        3    1203     Officer          HR  28.0       NaN       NaN
3        4    1005     Manager          HR  45.0  120000.0   30000.0
4        5    2123  Office Boy    Accounts  27.0   45000.0    4500.0
5        6    2451  Accountant         NaN  34.0  100000.0   25000.0
6        7    1111  Accountant    Accounts   NaN  110000.0   27500.0
7        8    1001     Officer          IT  25.0   75000.0    7500.0
8        9    1234     Manager          IT  23.0       NaN       NaN
9       10    2156    Engineer  Production  45.0   89000.0    8900.0
10      11    6543     Officer  Production  29.0  100000.0   25000.0
11      12    3214  Accountant     Account  49.0  123000.0   30750.0
12      13    2156    Engineer  Production  45.0   89000.0    8900.0
13      14    1098     Officer          IT  25.0  100000.0   25000.0
14      15    2912     Officer          IT  31.0   90000.0    9000.0
15      16    1222     Officer         NaN  25.0       NaN       NaN
16      17    2156    Engineer  Production  45.0   89000.0    8900.0
17      18    2123  Office Boy    Accounts  27.0   45000.0    4500.0

In [ ]:
emp['Bonus2'] = emp.Salary.apply(lambda sal:sal*0.5 if sal>=200000
                                 else sal*.3 if sal>=150000
                                 else sal*.1)
emp

    Serial  Emp_ID Designation  Department   Age    Salary     Bonus    Bonus2
0        1    1101     Manager    Accounts  50.0  200000.0  100000.0  100000.0
1        2    1107     Officer          IT  30.0   80000.0    8000.0    8000.0
2        3    1203     Officer          HR  28.0       NaN       NaN       NaN
3        4    1005     Manager          HR  45.0  120000.0   30000.0   12000.0
4        5    2123  Office Boy    Accounts  27.0   45000.0    4500.0    4500.0
5        6    2451  Accountant         NaN  34.0  100000.0   25000.0   10000.0
6        7    1111  Accountant    Accounts   NaN  110000.0   27500.0   11000.0
7        8    1001     Officer          IT  25.0   75000.0    7500.0    7500.0
8        9    1234     Manager          IT  23.0       NaN       NaN       NaN
9       10    2156    Engineer  Production  45.0   89000.0    8900.0    8900.0
10      11    6543     Officer  Production  29.0  100000.0   25000.0   10000.0
11      12    3214  Accountant     Account  49.0  123000.0   30750.0   12300.0
12      13    2156    Engineer  Production  45.0   89000.0    8900.0    8900.0
13      14    1098     Officer          IT  25.0  100000.0   25000.0   10000.0
14      15    2912     Officer          IT  31.0   90000.0    9000.0    9000.0
15      16    1222     Officer         NaN  25.0       NaN       NaN       NaN
16      17    2156    Engineer  Production  45.0   89000.0    8900.0    8900.0
17      18    2123  Office Boy    Accounts  27.0   45000.0    4500.0    4500.0

In [ ]:
# emp['Bonus3'] = emp.apply(lambda row:
#                           row['Salary']*.5 if row['Age']>=50
#                           else row['Salary']*.3 if row['Age']>=40
#                           else row['Salary']*.1, axis=1)
emp['Bonus3'] = emp.apply(lambda row: 
                          row['Salary'] * 0.5 if row['Age'] >= 50
                          else row['Salary'] * 0.3 if row['Age'] >= 40
                          else row['Salary'] * 0.25 if row['Age'] >= 30
                          else row['Salary'] * 0.1 , axis=1
                          )

emp

,Serial,Emp_ID,Designation,Department,Age,Salary,Bonus,Bonus2,Bonus3
0,1,1101,Manager,Accounts,50.0,200000.0,100000.0,100000.0,100000.0
1,2,1107,Officer,IT,30.0,80000.0,8000.0,8000.0,8000.0
2,3,1203,Officer,HR,28.0,NaN,NaN,NaN,NaN
3,4,1005,Manager,HR,45.0,120000.0,30000.0,12000.0,36000.0
4,5,2123,Office Boy,Accounts,27.0,45000.0,4500.0,4500.0,4500.0
5,6,2451,Accountant,NaN,34.0,100000.0,25000.0,10000.0,10000.0
6,7,1111,Accountant,Accounts,NaN,110000.0,27500.0,11000.0,11000.0
7,8,1001,Officer,IT,25.0,75000.0,7500.0,7500.0,7500.0
8,9,1234,Manager,IT,23.0,NaN,NaN,NaN,NaN
9,10,2156,Engineer,Production,45.0,89000.0,8900.0,8900.0,26700.0
10,11,6543,Officer,Production,29.0,100000.0,25000.0,10000.0,10000.0
11,12,3214,Accountant,Account,49.0,123000.0,30750.0,12300.0,36900.0
12,13,2156,Engineer,Production,45.0,89000.0,8900.0,8900.0,26700.0
13,14,1098,Officer,IT,25.0,100000.0,25000.0,10000.0,10000.0
14,15,2912,Officer,IT,31.0,90000.0,9000.0,9000.0,9000.0
15,16,1222,Officer,NaN,25.0,NaN,NaN,NaN,NaN
16,17,2156,Engineer,Production,45.0,89000.0,8900.0,8900.0,26700.0
17,18,2123,Office Boy,Accounts,27.0,45000.0,4500.0,4500.0,4500.0

In [12]:
emp.drop('Bonus',axis=1)

    Serial  Emp_ID Designation  Department   Age    Salary    Bonus2    Bonus3
0        1    1101     Manager    Accounts  50.0  200000.0  100000.0  100000.0
1        2    1107     Officer          IT  30.0   80000.0    8000.0    8000.0
2        3    1203     Officer          HR  28.0       NaN       NaN       NaN
3        4    1005     Manager          HR  45.0  120000.0   12000.0   36000.0
4        5    2123  Office Boy    Accounts  27.0   45000.0    4500.0    4500.0
5        6    2451  Accountant         NaN  34.0  100000.0   10000.0   10000.0
6        7    1111  Accountant    Accounts   NaN  110000.0   11000.0   11000.0
7        8    1001     Officer          IT  25.0   75000.0    7500.0    7500.0
8        9    1234     Manager          IT  23.0       NaN       NaN       NaN
9       10    2156    Engineer  Production  45.0   89000.0    8900.0   26700.0
10      11    6543     Officer  Production  29.0  100000.0   10000.0   10000.0
11      12    3214  Accountant     Account  49.0  123000.0   12300.0   36900.0
12      13    2156    Engineer  Production  45.0   89000.0    8900.0   26700.0
13      14    1098     Officer          IT  25.0  100000.0   10000.0   10000.0
14      15    2912     Officer          IT  31.0   90000.0    9000.0    9000.0
15      16    1222     Officer         NaN  25.0       NaN       NaN       NaN
16      17    2156    Engineer  Production  45.0   89000.0    8900.0   26700.0
17      18    2123  Office Boy    Accounts  27.0   45000.0    4500.0    4500.0

In [13]:
emp

,Serial,Emp_ID,Designation,Department,Age,Salary,Bonus,Bonus2,Bonus3
0,1,1101,Manager,Accounts,50.0,200000.0,100000.0,100000.0,100000.0
1,2,1107,Officer,IT,30.0,80000.0,8000.0,8000.0,8000.0
2,3,1203,Officer,HR,28.0,NaN,NaN,NaN,NaN
3,4,1005,Manager,HR,45.0,120000.0,30000.0,12000.0,36000.0
4,5,2123,Office Boy,Accounts,27.0,45000.0,4500.0,4500.0,4500.0
5,6,2451,Accountant,NaN,34.0,100000.0,25000.0,10000.0,10000.0
6,7,1111,Accountant,Accounts,NaN,110000.0,27500.0,11000.0,11000.0
7,8,1001,Officer,IT,25.0,75000.0,7500.0,7500.0,7500.0
8,9,1234,Manager,IT,23.0,NaN,NaN,NaN,NaN
9,10,2156,Engineer,Production,45.0,89000.0,8900.0,8900.0,26700.0
10,11,6543,Officer,Production,29.0,100000.0,25000.0,10000.0,10000.0
11,12,3214,Accountant,Account,49.0,123000.0,30750.0,12300.0,36900.0
12,13,2156,Engineer,Production,45.0,89000.0,8900.0,8900.0,26700.0
13,14,1098,Officer,IT,25.0,100000.0,25000.0,10000.0,10000.0
14,15,2912,Officer,IT,31.0,90000.0,9000.0,9000.0,9000.0
15,16,1222,Officer,NaN,25.0,NaN,NaN,NaN,NaN
16,17,2156,Engineer,Production,45.0,89000.0,8900.0,8900.0,26700.0
17,18,2123,Office Boy,Accounts,27.0,45000.0,4500.0,4500.0,4500.0

In [18]:
emp = emp.drop('Bonus2',axis=1)
emp

    Serial  Emp_ID Designation  Department   Age    Salary    Bonus3
0        1    1101     Manager    Accounts  50.0  200000.0  100000.0
1        2    1107     Officer          IT  30.0   80000.0    8000.0
2        3    1203     Officer          HR  28.0       NaN       NaN
3        4    1005     Manager          HR  45.0  120000.0   36000.0
4        5    2123  Office Boy    Accounts  27.0   45000.0    4500.0
5        6    2451  Accountant         NaN  34.0  100000.0   10000.0
6        7    1111  Accountant    Accounts   NaN  110000.0   11000.0
7        8    1001     Officer          IT  25.0   75000.0    7500.0
8        9    1234     Manager          IT  23.0       NaN       NaN
9       10    2156    Engineer  Production  45.0   89000.0   26700.0
10      11    6543     Officer  Production  29.0  100000.0   10000.0
11      12    3214  Accountant     Account  49.0  123000.0   36900.0
12      13    2156    Engineer  Production  45.0   89000.0   26700.0
13      14    1098     Officer          IT  25.0  100000.0   10000.0
14      15    2912     Officer          IT  31.0   90000.0    9000.0
15      16    1222     Officer         NaN  25.0       NaN       NaN
16      17    2156    Engineer  Production  45.0   89000.0   26700.0
17      18    2123  Office Boy    Accounts  27.0   45000.0    4500.0

In [19]:
del emp['Bonus3']
emp

    Serial  Emp_ID Designation  Department   Age    Salary
0        1    1101     Manager    Accounts  50.0  200000.0
1        2    1107     Officer          IT  30.0   80000.0
2        3    1203     Officer          HR  28.0       NaN
3        4    1005     Manager          HR  45.0  120000.0
4        5    2123  Office Boy    Accounts  27.0   45000.0
5        6    2451  Accountant         NaN  34.0  100000.0
6        7    1111  Accountant    Accounts   NaN  110000.0
7        8    1001     Officer          IT  25.0   75000.0
8        9    1234     Manager          IT  23.0       NaN
9       10    2156    Engineer  Production  45.0   89000.0
10      11    6543     Officer  Production  29.0  100000.0
11      12    3214  Accountant     Account  49.0  123000.0
12      13    2156    Engineer  Production  45.0   89000.0
13      14    1098     Officer          IT  25.0  100000.0
14      15    2912     Officer          IT  31.0   90000.0
15      16    1222     Officer         NaN  25.0       NaN
16      17    2156    Engineer  Production  45.0   89000.0
17      18    2123  Office Boy    Accounts  27.0   45000.0

In [20]:
emp.drop('Age',axis=1,inplace=True)
emp

    Serial  Emp_ID Designation  Department    Salary
0        1    1101     Manager    Accounts  200000.0
1        2    1107     Officer          IT   80000.0
2        3    1203     Officer          HR       NaN
3        4    1005     Manager          HR  120000.0
4        5    2123  Office Boy    Accounts   45000.0
5        6    2451  Accountant         NaN  100000.0
6        7    1111  Accountant    Accounts  110000.0
7        8    1001     Officer          IT   75000.0
8        9    1234     Manager          IT       NaN
9       10    2156    Engineer  Production   89000.0
10      11    6543     Officer  Production  100000.0
11      12    3214  Accountant     Account  123000.0
12      13    2156    Engineer  Production   89000.0
13      14    1098     Officer          IT  100000.0
14      15    2912     Officer          IT   90000.0
15      16    1222     Officer         NaN       NaN
16      17    2156    Engineer  Production   89000.0
17      18    2123  Office Boy    Accounts   45000.0

In [21]:
emp.head()

   Serial  Emp_ID Designation Department    Salary
0       1    1101     Manager   Accounts  200000.0
1       2    1107     Officer         IT   80000.0
2       3    1203     Officer         HR       NaN
3       4    1005     Manager         HR  120000.0
4       5    2123  Office Boy   Accounts   45000.0

In [22]:
emp.tail()

    Serial  Emp_ID Designation  Department    Salary
13      14    1098     Officer          IT  100000.0
14      15    2912     Officer          IT   90000.0
15      16    1222     Officer         NaN       NaN
16      17    2156    Engineer  Production   89000.0
17      18    2123  Office Boy    Accounts   45000.0

In [23]:
emp[5:12,'Serial':'Salary']

InvalidIndexError: (slice(5, 12, None), slice('Serial', 'Salary', None))

In [26]:
emp.iloc[5:9,0:3]

   Serial  Emp_ID Designation
5       6    2451  Accountant
6       7    1111  Accountant
7       8    1001     Officer
8       9    1234     Manager

In [27]:
emp.loc[5:9,'Serial':'Department']

   Serial  Emp_ID Designation  Department
5       6    2451  Accountant         NaN
6       7    1111  Accountant    Accounts
7       8    1001     Officer          IT
8       9    1234     Manager          IT
9      10    2156    Engineer  Production